### ISSUE TITLE
Add Redo support

### ISSUE THREAD

**Issue by naclcaleb** [naclcaleb/Draw#11]
Currently I have the "undo" command working with the shortcut Ctrl+Z, but it doesn't do redo. 

I already have all the infrastructure for handling redos though. The "Layer" class stores an "undone" array that is updated whenever "undo" is called. All you have to do to add the feature is add a key listener for Ctrl+Y, and when that happens, do the following:

1. Put the first element in the "undone" array into the "strokes" array (this is inside the Layer class, so they'll be `this.undone` and `this.strokes`). The first element should be deleted from the `undone` array.

2. Now call the `updateRender` function on the Layer class (`this.updateRender()`).

@OOPS-Studio, I was wondering if you might want to take this up?

**Comment by OOPS-Studio** [comment]
How offensive! ;3 Giving me the super easy job! :3 Well, I could... XD I wasn't really planning on it, though... ;)

**Comment by naclcaleb** [comment]
Hey, if you want to tackle the multiple layers issue too, that'd be fine xD :P

**Comment by OOPS-Studio** [comment]
1. Hahaha, I'm not a Python-er myself! ;) If it was C++, though.. XD
2. Yep! :) I totally understand! ;) I was just making a joke! ;3

**Comment by naclcaleb** [comment]
1. 👍 
2. 👍

**Comment by OOPS-Studio** [comment]
Working on that now! ;) (Trying to adapt to your code! ;3)

**Comment by naclcaleb** [comment]
In case you hadn't already noticed, you might want to look in `Layer.js`.

I cleaned the code up just today, so it should be somewhat readable.

**Comment by OOPS-Studio** [comment]
1. I found that out! ;3
2. Yeah! It's nice code, dude! :)

**Comment by naclcaleb** [comment]
1. Great
2. Thanks!

**Comment by OOPS-Studio** [comment]
Note: Why do you `unshift()` the undos so you can `shift()` them back, instead of `push()` and `pop()` ?

**Comment by OOPS-Studio** [comment]
1. :)
2. 👍

**Comment by naclcaleb** [comment]
Oh, as for your note, it's just the way I think about it. Either one would work fine.

**Comment by OOPS-Studio** [comment]
Okay! :) Sounds good! ;) I just added redoing, I'm not sure if it works yet, as I have no easy way to test it, but I'm about to push it to you! ;)

**Comment by naclcaleb** [comment]
It seems like you don't have a keyboard event listener on it. It should be similar to lines 40-49 in `Canvas.js`

**Comment by OOPS-Studio** [comment]
Ah! Duh! XD For some reason I figured you add that! ;3 I'll fix it! :)
