### ISSUE TITLE
Problem undoing/redoing

### ISSUE THREAD

**Issue by OOPS-Studio** [naclcaleb/Draw#14]
So, I have a weird problem... When I undo and then redo and then try to undo again, it doesn't do anything. If I try to undo enough times then the screen starts to flash, and then the whole drawing disappears... Hope we can find a fix for this! ;) (More like, you find a fix if I'm not successful in the next 5 seconds! ;3) (Sorry for all the sarcasm... If you don't like it, I'll stop! 👍 )

**Comment by naclcaleb** [comment]
Hm... in theory you should be able to undo a redo anyway, since the undo would be popping what the redo just pushed. 

I'll have to look into this later.

In the meantime, feel free to make another PR if you want.

**Comment by OOPS-Studio** [comment]
Ayy! I think I fixed it! ;) It was a problem on my side! :) The problem was, I was `unshifting()` to the `strokes` array, and when you undo it `pops()` from the `strokes` array! ;) I made a new PR, you can test it and merge it if it works! :) (If so, I will close this issue! 👍 )

**Comment by naclcaleb** [comment]
Yea, I realized that to!

Nice job! I'll try when I can.

**Comment by OOPS-Studio** [comment]
1. Haha! XD Okay! ;)
2. Thanks! ;3 Kewlness! :)

**Comment by OOPS-Studio** [comment]
Wait... YOU CLOSED MY ISSUE!? ARRGGG! >:( I wanted to do it. >:l (JK, JK, Thanks! ;))

**Comment by OOPS-Studio** [comment]
Ahhhh! I see! :) That's pretty kewl! ;)
