### ISSUE TITLE
Having to undo all redos.

### ISSUE THREAD

**Issue by OOPS-Studio** [naclcaleb/Draw#17]
When I undo 4 times, and then redo 4 times, and then undo 4 times, all's good. However, if I undo 5 times and then redo 10 times, then I have to undo 5 times before the undos will start doing anything! :) I'll start working on that now! :)

**Comment by naclcaleb** [comment]
Alright, I'll let you close this one :P

**Comment by OOPS-Studio** [comment]
Yay! XD
