### ISSUE TITLE
`python -m SimpleHTTPServer` command not working

### ISSUE THREAD

**Issue by rocketbear27** [naclcaleb/Draw#6]
In you `README.md` file, you state to run the `python -m SimpleHTTPServer` or run on an apache server (which is not an option). Is there something I need to configure to run the command?

This is the output:
``` powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\rocke\Desktop\Draw> python -m SimpleHTTPServer
C:\Users\rocke\AppData\Local\Programs\Python\Python37-32\python.exe: No module named SimpleHTTPServer
PS C:\Users\rocke\Desktop\Draw>
```

**Comment by naclcaleb** [comment]
Try `python -m http.server 8000`.

**Comment by naclcaleb** [comment]
And I accidentally broke the main drawing functions. I'm working on fixing it, but it won't be that impressive right now.

**Comment by naclcaleb** [comment]
You could also just view it at https://naclcaleb.github.io/Draw

**Comment by naclcaleb** [comment]
Did you try it?

**Comment by rocketbear27** [comment]
This still does not work, even with the new command. I could just view it on your website. But I feel like this is still a bug for during dev mode.

![capture](https://user-images.githubusercontent.com/40366354/51356737-9fbaf580-1a70-11e9-8ad3-d346646b405d.PNG)

**Comment by naclcaleb** [comment]
Don't go to `0.0.0.0:8000`, go to `localhost:8000` or `127.0.0.1:8000`

**Comment by rocketbear27** [comment]
What file includes in building the server?

**Comment by naclcaleb** [comment]
I'm not sure what you mean...

**Comment by rocketbear27** [comment]
Isn't there a file that routes this server or does python auto creates a server?

**Comment by naclcaleb** [comment]
Python auto creates it.
